In [1]:
import pandas as pd

df = pd.read_csv('../data/wine_data.csv')
df

Alcohol  Malic   Ash  Alcalinity  Magesium  Phenols  Flavanoids  \
0      14.23   1.71  2.43        15.6       127     2.80        3.06   
1      13.20   1.78  2.14        11.2       100     2.65        2.76   
2      13.16   2.36  2.67        18.6       101     2.80        3.24   
3      14.37   1.95  2.50        16.8       113     3.85        3.49   
4      13.24   2.59  2.87        21.0       118     2.80        2.69   
..       ...    ...   ...         ...       ...      ...         ...   
173    13.71   5.65  2.45        20.5        95     1.68        0.61   
174    13.40   3.91  2.48        23.0       102     1.80        0.75   
175    13.27   4.28  2.26        20.0       120     1.59        0.69   
176    13.17   2.59  2.37        20.0       120     1.65        0.68   
177    14.13   4.10  2.74        24.5        96     2.05        0.76   

     Nonflavanoids  Proanthocyanins  Color   Hue  Dilution  Proline  class  
0             0.28             2.29   5.64  1.04      3.92     1065      0  
1             0.26             1.28   4.38  1.05      3.40     1050      0  
2             0.30             2.81   5.68  1.03      3.17     1185      0  
3             0.24             2.18   7.80  0.86      3.45     1480      0  
4             0.39             1.82   4.32  1.04      2.93      735      0  
..             ...              ...    ...   ...       ...      ...    ...  
173           0.52             1.06   7.70  0.64      1.74      740      2  
174           0.43             1.41   7.30  0.70      1.56      750      2  
175           0.43             1.35  10.20  0.59      1.56      835      2  
176           0.53             1.46   9.30  0.60      1.62      840      2  
177           0.56             1.35   9.20  0.61      1.60      560      2  

[178 rows x 14 columns]

In [2]:
from my_functions import create_feature_target, clf_eval

X_train, X_test, y_train, y_test = create_feature_target(df)

In [4]:
from sklearn import svm
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV

param_grid = {
    'kernel' : ['linear', 'rbf'],
    'C' : [0.5, 1, 10, 100]
}
# kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
svc = svm.SVC(random_state=0)
grid_cv = GridSearchCV(svc, param_grid=param_grid, cv=5, scoring='accuracy')
grid_cv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(random_state=0),
             param_grid={'C': [0.5, 1, 10, 100], 'kernel': ['linear', 'rbf']},
             scoring='accuracy')

In [5]:
grid_cv.cv_results_

{'mean_fit_time': array([0.00260859, 0.00160069, 0.00320363, 0.        , 0.        ,
        0.0015986 , 0.00320029, 0.        ]),
 'std_fit_time': array([0.00332309, 0.00320139, 0.00392364, 0.        , 0.        ,
        0.00319719, 0.00391954, 0.        ]),
 'mean_score_time': array([0.00384636, 0.00159988, 0.00319986, 0.00159569, 0.00301361,
        0.        , 0.00159926, 0.00319963]),
 'std_score_time': array([0.00362378, 0.00319977, 0.00391903, 0.00319138, 0.00370355,
        0.        , 0.00319853, 0.00391872]),
 'param_C': masked_array(data=[0.5, 0.5, 1, 1, 10, 10, 100, 100],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 0.5, 'k

In [6]:
import numpy as np

np.transpose(pd.DataFrame(grid_cv.cv_results_))

0  \
mean_fit_time                            0.002609   
std_fit_time                             0.003323   
mean_score_time                          0.003846   
std_score_time                           0.003624   
param_C                                       0.5   
param_kernel                               linear   
params             {'C': 0.5, 'kernel': 'linear'}   
split0_test_score                        0.931034   
split1_test_score                        0.862069   
split2_test_score                        0.964286   
split3_test_score                        0.964286   
split4_test_score                        0.964286   
mean_test_score                          0.937192   
std_test_score                           0.039708   
rank_test_score                                 5   

                                             1                             2  \
mean_fit_time                         0.001601                      0.003204   
std_fit_time                          0.003201                      0.003924   
mean_score_time                         0.0016                        0.0032   
std_score_time                          0.0032                      0.003919   
param_C                                    0.5                             1   
param_kernel                               rbf                        linear   
params             {'C': 0.5, 'kernel': 'rbf'}  {'C': 1, 'kernel': 'linear'}   
split0_test_score                     0.965517                      0.931034   
split1_test_score                          1.0                      0.862069   
split2_test_score                          1.0                      0.964286   
split3_test_score                          1.0                      0.964286   
split4_test_score                     0.964286                      0.964286   
mean_test_score                       0.985961                      0.937192   
std_test_score                        0.017199                      0.039708   
rank_test_score                              1                             5   

                                           3                              4  \
mean_fit_time                            0.0                            0.0   
std_fit_time                             0.0                            0.0   
mean_score_time                     0.001596                       0.003014   
std_score_time                      0.003191                       0.003704   
param_C                                    1                             10   
param_kernel                             rbf                         linear   
params             {'C': 1, 'kernel': 'rbf'}  {'C': 10, 'kernel': 'linear'}   
split0_test_score                   0.965517                       0.931034   
split1_test_score                        1.0                       0.862069   
split2_test_score                        1.0                       0.964286   
split3_test_score                        1.0                       0.964286   
split4_test_score                   0.964286                       0.964286   
mean_test_score                     0.985961                       0.937192   
std_test_score                      0.017199                       0.039708   
rank_test_score                            1                              5   

                                            5                               6  \
mean_fit_time                        0.001599                          0.0032   
std_fit_time                         0.003197                         0.00392   
mean_score_time                           0.0                        0.001599   
std_score_time                            0.0                        0.003199   
param_C                                    10                             100   
param_kernel                              rbf                          linear   
params             {'C': 10, 'kernel': 'rbf'}  {'C': 100, 'kernel': 'linear'}   
split

In [7]:
grid_cv.best_score_

0.9859605911330049

In [8]:
grid_cv.best_params_

{'C': 0.5, 'kernel': 'rbf'}

In [9]:
grid_cv.best_estimator_

SVC(C=0.5, random_state=0)

In [10]:
best_model = grid_cv.best_estimator_
best_model.fit(X_train, y_train)

# 재학습된 모델로 예측 수행
y_pred = best_model.predict(X_test)

from my_functions import clf_eval
clf_eval(y_test, y_pred)

<evaluate>
accuracy: 1.0
precision: 1.0
recall: 1.0
f1: 1.0
<confusion matrix>
 [[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
<class report>
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         6

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

