### Tf-idf와 코사인 유사도

언어모델 : 통계적 모델, 신경망(기반) 모델   
나는 오늘 강의실에서 자연어처리를 ?   
통계적 모델 : 단어의 순서에 대해 확률이 부여   
P(나는 자연어 처리를 공부한다) > P(나는 자연어 처리를 먹는다)   
P(공부한다|나는, 자연어, 처리를)   
n-gram : 문서(장,단)간 유사   
'오늘 점심 추천 메뉴:소고기볶음밥, 햄볶음밥'   
유니그램(n=1) : 오늘, 점심, 추천, 메뉴,소고기볶음밥, 햄볶음밥   
바이그램(n=2) : 오늘 점심,점심 추천,추천 메뉴,메뉴 소고기볶음밥,소고기볶음밥 햄볶음밥   
Trigram(n=3)   
...   
P(소고기볶음밥|점심 추천 메뉴)=   
 count(점심 추천 메뉴 소고기볶음밥)   / count(점심 추천 메뉴)   
 = 20/30   
P(햄볶음밥|점심 추천 메뉴)=   
 count(점심 추천 메뉴 햄볶음밥)   / count(점심 추천 메뉴)   
 = 5/30   
...   
점심 추천 메뉴 ?(소고기볶음밥)   
*시간이 되면 LCS(Longest Common Subsequence) 알고리즘 공부   

1. 한국어는 단어의 순서가 큰 의미 없음 -> 신경망 기반 생성시 어려움   
Linear Regression(회귀) -> Logistic Regression(이중분류, sigmoid) -> SOFTMAX(다중분류) -> (얕은)신경망(입력과 출려계층 존재) : NN   
(깊은)신경망(입력/히든/출력) 종류 : DNN, CNN, RNN 등   

h(x) = wx + b
sigmoid(h(x)) = 1 / (1+e-(h(x))) (0~1 사이 결과)

In [3]:
"""
one-hot, DTM(Document Term Matrix, TF), TDM,  TFIDF(TF*IDF)
      단어1 단어2 ... 단어M
문서1   5     0   ...   1      M차원벡터공간(5,0,...,1)
문서2
...
문서N
"""

'\none-hot, DTM(Document Term Matrix, TF), TDM,  TFIDF(TF*IDF)\n      단어1 단어2 ... 단어M\n문서1   5     0   ...   1      M차원벡터공간(5,0,...,1)\n문서2\n...\n문서N\n'

In [11]:
# 단어의 빈도수로 벡터 생성
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
corpus = ['나는 지금 자연어 처리를 공부해요. 나는 자연어 좋아요.']

vector = CountVectorizer()

In [15]:
# fit : 각각의 단어별로 인덱스 부여
# transform : corpus에 저장된 문장을 fit 결과에 맞춰 변환(빈도수)해라 => [2 1 2 1 1 1]
vector.fit_transform(corpus)

<1x6 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [16]:
vector.fit_transform(corpus).toarray()

array([[1, 2, 2, 1, 1, 1]], dtype=int64)

In [17]:
vector.vocabulary_

{'나는': 1, '지금': 4, '자연어': 2, '처리를': 5, '공부해요': 0, '좋아요': 3}

tf(d, t) : 문서 d에서 단어 t의 등장 횟수   
df(t) : 단어 t가 등장한 문서의 개수
idf(d, t) : log(n / (df(t) + 1))
- n은 전체 문서의 개수
- log

ex) n=1000   
idf(d,t)=log(1000 / (df(t)+1))   
df(t) =1, idf(d,t)는 log(1000/1)은 3   
df(t) =10, idf(d,t)는 log(1000/10)은 2

In [29]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [30]:
corpus = [
    'I love you', # 문서 1
    'I can do it', # 문서 2 
    'I want your love' # 문서 3
]

In [31]:
v = CountVectorizer()
tf_idf = TfidfVectorizer()

In [35]:
v.fit_transform(corpus).toarray()

array([[0, 0, 0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 1]], dtype=int64)

In [36]:
tf_idf.fit_transform(corpus).toarray()

array([[0.        , 0.        , 0.        , 0.60534851, 0.        ,
        0.79596054, 0.        ],
       [0.57735027, 0.57735027, 0.57735027, 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.4736296 , 0.62276601,
        0.        , 0.62276601]])

In [33]:
v.vocabulary_

{'love': 3, 'you': 5, 'can': 0, 'do': 1, 'it': 2, 'want': 4, 'your': 6}

In [34]:
tf_idf.vocabulary_

{'love': 3, 'you': 5, 'can': 0, 'do': 1, 'it': 2, 'want': 4, 'your': 6}

In [38]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

In [39]:
#d1,d2,d3는 영화제목
#각 열은 영화 대사에 등장한 단어(사랑,돈,운명,증오)
d1=np.array([1,1,1,0]) #루트2
d2=np.array([0,1,1,1])
d3=np.array([0,5,5,5]) #루트48
#유클리디안 거리 공식으로는 d2문서가 d1과 가까움

In [40]:
dot(d1, d2) / (norm(d1)*norm(d2)) #0.67

0.6666666666666667

In [41]:
dot(d3, d2) / (norm(d3)*norm(d2)) #1

1.0

**자카드 유사도(집합의 원소는 단어에 해당됨)**      

자카드유사도(d1, d2) = (d1 교집합 d2) / (d1 합집합 d2)

### 영화 추천

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

df = pd.read_csv('../Data/movies_metadata.csv')
df.head(3)

C:\Users\parkm\AppData\Local\Temp\ipykernel_13612\959188786.py:5: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../Data/movies_metadata.csv')


adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
2                                   NaN  15602  tt0113228                en   

     original_title                                           overview  ...  \
0         Toy Story  Led by Woody, Andy's toys live happily in his ...  ...   
1           Jumanji  When siblings Judy and Peter discover an encha...  ...   
2  Grumpier Old Men  A family wedding reignites the ancient feud be...  ...   

  release_date      revenue runtime  \
0   1995-10-30  373554033.0    81.0   
1   1995-12-15  262797249.0   104.0   
2   1995-12-22          0.0   101.0   

                                    spoken_languages    status  \
0           [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released   
2           [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                             tagline             title  video  \
0                                                NaN         Toy Story  False   
1          Roll the dice and unleash the excitement!           Jumanji  False   
2  Still Yelling. Still Fighting. Still Ready for...  Grumpier Old Men  False   

  vote_average vote_count  
0          7.7     5415.0  
1          6.9     2413.0  
2          6.5       92.0  

[3 rows x 24 columns]

In [2]:
df = df[['original_title', 'overview']].iloc[:10000]
df.head(3)

original_title                                           overview
0         Toy Story  Led by Woody, Andy's toys live happily in his ...
1           Jumanji  When siblings Judy and Peter discover an encha...
2  Grumpier Old Men  A family wedding reignites the ancient feud be...

In [3]:
df.shape

(10000, 2)

In [4]:
df.fillna('', inplace=True)

In [5]:
df['overview'].isnull().values.any()    # 결손 데이터 없는 것 확인

False

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english', min_df=3)     # 크게 의미없는 단어들을 제외해준다.
tfidf_matrix = tfidf.fit_transform(df['overview'])
tfidf_matrix.shape

(10000, 12479)

In [7]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)     # 코사인 유사도 계산
cosine_sim.shape

(10000, 10000)

In [8]:
cosine_sim

array([[1.        , 0.01758412, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01758412, 1.        , 0.05307289, ..., 0.        , 0.01596929,
        0.        ],
       [0.        , 0.05307289, 1.        , ..., 0.        , 0.01010516,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.09361866],
       [0.        , 0.01596929, 0.01010516, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.09361866, 0.        ,
        1.        ]])

In [9]:
indices = pd.Series(df.index, index=df['original_title']).drop_duplicates()    # 중복 제거
indices

original_title
Toy Story                           0
Jumanji                             1
Grumpier Old Men                    2
Waiting to Exhale                   3
Father of the Bride Part II         4
                                 ... 
Miracolo a Milano                9995
Napola – Elite für den Führer    9996
The Frisco Kid                   9997
Onmyoji                          9998
State Property 2                 9999
Length: 10000, dtype: int64

In [10]:
# 음식명을 입력받으면 코사인 유사도를 통해서 가장 유사도가 높은 상위 10개의 음식 목록 반환
def get_recommendations(title, cosine_sim=cosine_sim):

  # 영화 제목을 통해서 전체 데이터 기준 그 영화의 index 값을 얻기
  idx = indices[title]

  # 코사인 유사도 매트릭스 (cosine_sim) 에서 idx 에 해당하는 데이터를 (idx, 유사도) 형태로 얻기
  sim_scores = list(enumerate(cosine_sim[idx]))

  # 코사인 유사도 기준으로 내림차순 정렬
  sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

  # 자기 자신을 제외한 10개의 추천 영화를 슬라이싱
  sim_scores = sim_scores[1:11]

  # 추천 영화목록 10개의 인덱스 정보 추출
  movie_indices = [i[0] for i in sim_scores]

  # 인덱스 정보를 통해 영화 제목 추출
  return df['original_title'].iloc[movie_indices]

In [11]:
get_recommendations('Toy Story')

2997                                    Toy Story 2
8327                                      The Champ
5797                                  Class of 1984
1071                          Rebel Without a Cause
6944                               Rivers and Tides
1932                                      Condorman
485                                          Malice
3057                                Man on the Moon
7615    The First $20 Million Is Always the Hardest
5618                                     Heartbeeps
Name: original_title, dtype: object

In [12]:
get_recommendations('Jumanji')

9503               Word Wars
6166               Brainscan
8801                 Quintet
8079                 Masques
3872      Dungeons & Dragons
7906    The Last Starfighter
6055        Poolhall Junkies
2486                eXistenZ
9369             성냥팔이 소녀의 재림
9107                 Nirvana
Name: original_title, dtype: object