# 데이터 구조의 이해 (4) - Tensor
- pytorch installation: https://pytorch.org/get-started/locally/
1. cpu installation: `pip install torch torchvision torchaudio`
1. gpu instalation: `pip install` 또는 `conda install`로 OS, CUDA 버전에 맞게 설치

In [6]:
import torch
torch.__version__

'2.0.1+cpu'

## 1. Simple CPU Example

In [2]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[7,8,9],[10,11,12]])
z = x + y

print(z) 
print(z.size()) 

tensor([[ 8, 10, 12],
        [14, 16, 18]])
torch.Size([2, 3])


## 2. Simple GPU Example

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x = torch.tensor([[1,2,3],
                  [4,5,6]], device=device)
y = torch.tensor([[7,8,9],
                  [10,11,12]], device=device)
z = x + y

print(z.size())
print(z.device)

torch.Size([2, 3])
cpu


## 3. Moving Tensors CPU & GPU

In [7]:
device = "cuda" if torch.cuda.is_available() else "cpu"

x.to(device)
y.to(device)

z = x + y
z.to("cpu")

tensor([[ 8, 10, 12],
        [14, 16, 18]])

## 4. Tensors 생성

In [8]:
import numpy 

w1 = torch.tensor([1,2,3])
w2 = torch.tensor((1,2,3)) 
w3 = torch.tensor(numpy.array([1,2,3])) 

print(w1, w2, w3)

tensor([1, 2, 3]) tensor([1, 2, 3]) tensor([1, 2, 3], dtype=torch.int32)


In [9]:
w4 = torch.empty(3,3) 
w5 = torch.zeros(4,4) 
w6 = torch.ones(5,5) 

print(w4, w5, w6)
print(w4.shape, w5.shape, w6.shape) 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
torch.Size([3, 3]) torch.Size([4, 4]) torch.Size([5, 5])


In [10]:
w7 = torch.rand(4,4)   
w8 = torch.randn(4,4)   
w9 = torch.randint(4, 10, (4,4)) 
print(w7, w8, w9)

tensor([[0.8740, 0.8263, 0.6071, 0.5184],
        [0.0559, 0.9969, 0.2647, 0.2324],
        [0.3972, 0.2889, 0.7804, 0.3805],
        [0.4452, 0.6120, 0.6309, 0.1816]]) tensor([[ 1.0792,  2.2401, -0.2091, -0.2217],
        [-0.8278, -0.5067,  0.0789,  1.3663],
        [-1.6561,  0.7945,  0.3220,  0.7661],
        [-0.8429, -1.2088, -0.9730,  1.2078]]) tensor([[8, 8, 5, 9],
        [4, 8, 5, 4],
        [6, 7, 6, 7],
        [8, 9, 9, 4]])


In [12]:
w10 = torch.empty((3,4), dtype=torch.float64, 
                device=device)

x = torch.empty_like(w10)
x

tensor([[7.5659e-307, 1.3796e-306, 1.0570e-307, 1.9582e-306],
        [2.2252e-306, 9.4574e-308, 6.2304e-307, 6.2305e-307],
        [9.3461e-307, 8.4559e-307, 9.3460e-307, 1.8692e-306]],
       dtype=torch.float64)

## 6. Torch Tensors 데이터 타입

In [13]:
w11 = torch.tensor([1,2,3], 
                   dtype=torch.float32)

w12 = w11.int()   # w changes to int32 after cast

print(w11, w12)

tensor([1., 2., 3.]) tensor([1, 2, 3], dtype=torch.int32)


In [14]:
w13 = w11.to(torch.float64) 
w14 = w11.to(dtype=torch.float64) 

print(w13, w14)

tensor([1., 2., 3.], dtype=torch.float64) tensor([1., 2., 3.], dtype=torch.float64)


In [15]:
x = torch.tensor([1,2,3], 
                 dtype=torch.int32)
y = torch.tensor([1,2,3], 
                 dtype=torch.float32)

z = x + y
print(z)
print(z.dtype)

tensor([2., 4., 6.])
torch.float32


## 7. Tensor 인덱싱, 슬라이싱

In [16]:
x = torch.tensor([[1,2],
                  [3,4],
                  [5,6],
                  [7,8]])

print(x[1,1])

print(x[1,1].item())

tensor(4)
4


In [17]:
# Slicing
x[:2, 1]
x[x < 5]

tensor([1, 2, 3, 4])

In [18]:
# 전치 transpose
print(x.t())

# view() 함수 = numpy의 reshape()와 동일
x.view((2,4))

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])


tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [19]:
# stack 함수로 합치기
y = torch.stack((x, x))
print(y)

# unbind로 분리하기
a,b = x.unbind(dim=1)
print(a,b)

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])
tensor([1, 3, 5, 7]) tensor([2, 4, 6, 8])


## 8. Automatic Differentiation (Autograd)

In [20]:
x = torch.tensor([[1,2,3],
                  [4,5,6]], 
                  dtype=torch.float, 
                  requires_grad=True)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

In [21]:
f = x.pow(2).sum()
f

tensor(91., grad_fn=<SumBackward0>)

In [22]:
f.backward()
x.grad # df/dx = 2x 

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])